import type { DemoRole } from "@/demo/model";

export const workspaceSections = [
  "dashboard",
  "ai-procurement",
  "golden-thread",
  "purchase-requests",
  "rfqs",
  "approvals",
  "purchase-orders",
  "receiving",
  "mobile-work",
  "inventory",
  "invoices",
  "vendors",
  "supplier-onboarding",
  "vendor-risk",
  "contracts",
  "contract-intelligence",
  "analytics",
  "reporting-studio",
  "audit-center",
  "trust-center",
  "accessibility-center",
  "administration",
  "integration-center",
  "enterprise-access",
  "workflow-studio",
  "operations-center",
  "settings",
] as const;

export type WorkspaceSection = (typeof workspaceSections)[number];

const allSections = new Set<WorkspaceSection>(workspaceSections);

const roleSections: Record<DemoRole, ReadonlySet<WorkspaceSection>> = {
  requester: new Set([
    "dashboard",
    "ai-procurement",
    "purchase-requests",
    "inventory",
    "vendors",
    "contracts",
    "settings",
  ]),
  department_manager: new Set([
    "dashboard",
    "ai-procurement",
    "purchase-requests",
    "approvals",
    "inventory",
    "analytics",
    "reporting-studio",
    "settings",
  ]),
  it_reviewer: new Set([
    "dashboard",
    "ai-procurement",
    "purchase-requests",
    "approvals",
    "inventory",
    "vendors",
    "vendor-risk",
    "contracts",
    "analytics",
    "audit-center",
    "settings",
  ]),
  purchasing_specialist: new Set([
    "dashboard",
    "ai-procurement",
    "purchase-requests",
    "rfqs",
    "approvals",
    "purchase-orders",
    "receiving",
    "inventory",
    "invoices",
    "vendors",
    "supplier-onboarding",
    "vendor-risk",
    "contracts",
    "contract-intelligence",
    "analytics",
    "reporting-studio",
    "audit-center",
    "settings",
  ]),
  purchasing_manager: new Set(
    workspaceSections.filter(
      (section) =>
        ![
          "administration",
          "enterprise-access",
          "workflow-studio",
          "operations-center",
        ].includes(section),
    ),
  ),
  finance_reviewer: new Set([
    "dashboard",
    "ai-procurement",
    "approvals",
    "purchase-orders",
    "receiving",
    "invoices",
    "supplier-onboarding",
    "contracts",
    "analytics",
    "reporting-studio",
    "audit-center",
    "integration-center",
    "settings",
  ]),
  compliance_reviewer: new Set([
    "dashboard",
    "ai-procurement",
    "approvals",
    "rfqs",
    "vendors",
    "supplier-onboarding",
    "vendor-risk",
    "contracts",
    "contract-intelligence",
    "analytics",
    "reporting-studio",
    "audit-center",
    "trust-center",
    "settings",
  ]),
  receiving_clerk: new Set([
    "dashboard",
    "ai-procurement",
    "purchase-orders",
    "receiving",
    "mobile-work",
    "inventory",
    "audit-center",
    "settings",
  ]),
  accounts_payable: new Set([
    "dashboard",
    "ai-procurement",
    "purchase-orders",
    "receiving",
    "invoices",
    "vendors",
    "analytics",
    "reporting-studio",
    "audit-center",
    "settings",
  ]),
  executive: new Set([
    "dashboard",
    "ai-procurement",
    "golden-thread",
    "purchase-requests",
    "approvals",
    "purchase-orders",
    "receiving",
    "inventory",
    "invoices",
    "vendors",
    "vendor-risk",
    "contracts",
    "analytics",
    "reporting-studio",
    "audit-center",
    "trust-center",
    "settings",
  ]),
  auditor: new Set([
    "dashboard",
    "ai-procurement",
    "purchase-requests",
    "rfqs",
    "approvals",
    "purchase-orders",
    "receiving",
    "inventory",
    "invoices",
    "vendors",
    "supplier-onboarding",
    "vendor-risk",
    "contracts",
    "contract-intelligence",
    "analytics",
    "reporting-studio",
    "audit-center",
    "trust-center",
    "accessibility-center",
    "integration-center",
    "settings",
  ]),
  supplier_user: new Set([
    "dashboard",
    "rfqs",
    "supplier-onboarding",
    "settings",
  ]),
  contract_manager: new Set([
    "dashboard",
    "ai-procurement",
    "vendors",
    "vendor-risk",
    "contracts",
    "contract-intelligence",
    "analytics",
    "reporting-studio",
    "audit-center",
    "settings",
  ]),
  security_reviewer: new Set([
    "dashboard",
    "ai-procurement",
    "supplier-onboarding",
    "vendor-risk",
    "contracts",
    "contract-intelligence",
    "audit-center",
    "trust-center",
    "accessibility-center",
    "enterprise-access",
    "operations-center",
    "settings",
  ]),
  operations_manager: new Set([
    "dashboard",
    "ai-procurement",
    "golden-thread",
    "reporting-studio",
    "audit-center",
    "trust-center",
    "accessibility-center",
    "integration-center",
    "enterprise-access",
    "workflow-studio",
    "operations-center",
    "settings",
  ]),
  system_administrator: allSections,
};

export function isWorkspaceSection(value: string): value is WorkspaceSection {
  return allSections.has(value as WorkspaceSection);
}

export function canAccessWorkspaceSection(
  role: DemoRole,
  section: string,
) {
  return (
    isWorkspaceSection(section) &&
    roleSections[role].has(section)
  );
}

export function canAccessWorkspacePath(role: DemoRole, path: string) {
  const section = path.split("/").filter(Boolean)[0];
  return section ? canAccessWorkspaceSection(role, section) : false;
}
