import {
  addBusinessDays,
  addCalendarDays,
} from "@/demo/clock";
import type {
  AssuranceControl,
  CapabilityRecord,
  CanonicalEntityDefinition,
  CertifiedMeasure,
  GoldenThreadScene,
  PhaseThreeState,
  ReportDefinition,
  RunbookRecord,
} from "@/phase-three/model";

export const PHASE_THREE_DATASET_VERSION = "phase3-commercialization-demo-v1";
export const PHASE_THREE_DATASET_HASH =
  "50faccb63005c02769277b8b1a9c3136fe1d39d17682daad4f2063dee0146afd";
export const PHASE_THREE_RELEASE_BASELINE =
  "0c9ce49ea3e07bc14dc47d3093dc3d5640170cc0";

function timestamp(date: string, hour = 14) {
  return `${date}T${String(hour).padStart(2, "0")}:00:00.000Z`;
}

function capability(
  capabilityId: string,
  name: string,
  owningModule: string,
  status: CapabilityRecord["status"],
  description: string,
  knownLimitations: string,
  activationRequirements: string,
): CapabilityRecord {
  return {
    capabilityId,
    name,
    description,
    owningModule,
    status,
    implementationEvidence: [
      `Phase 3 ${owningModule} implementation`,
      `Automated ${capabilityId} control tests`,
    ],
    dataSource:
      status === "Live"
        ? "Verified deployed provider and synthetic Catalyst records"
        : "Versioned Catalyst synthetic demonstration dataset",
    providerDependency:
      status === "Live" ? "Configured deployment provider" : undefined,
    customerDependency:
      status === "Future Activation"
        ? "Customer-approved configuration and credentials"
        : undefined,
    securityConsiderations:
      "Tenant, persona, evidence, simulation, and audit controls apply.",
    knownLimitations,
    activationRequirements,
    releaseFirstVerified: undefined,
    lastVerificationResult: "not_run",
    owner: `${owningModule} owner`,
    version: 1,
  };
}

export const phaseThreeCapabilityRegistry: CapabilityRecord[] = [
  capability(
    "CAP-TRUTH-001",
    "Capability truth registry",
    "Platform",
    "Functional Demo",
    "One versioned source controls capability status, evidence, limitations, and activation requirements.",
    "Verification results remain release-specific.",
    "Pass registry reconciliation and release-manifest checks.",
  ),
  capability(
    "CAP-DATA-001",
    "Versioned synthetic scenario",
    "Platform",
    "Functional Demo",
    "A deterministic, internally coherent synthetic enterprise procurement scenario.",
    "No customer records or realized customer outcomes are represented.",
    "Customer data remains prohibited until pilot activation.",
  ),
  capability(
    "CAP-SUPABASE-001",
    "Supabase authority and private evidence",
    "Platform",
    "Functional Demo",
    "Supabase Auth, Postgres, RLS, and private Storage are used when staging is configured.",
    "Local development uses a labeled temporary server fallback.",
    "Configure and verify the isolated Phase 3 Supabase staging project.",
  ),
  capability(
    "CAP-INTEGRATION-001",
    "Canonical file exchange",
    "Integration Center",
    "Functional Demo",
    "Versioned CSV/file-style staging, mapping, validation, reconciliation, retry, replay, and reversal.",
    "No customer SFTP server is contacted.",
    "Select and approve a customer transport during pilot activation.",
  ),
  capability(
    "CAP-ERP-001",
    "ERP and accounting connection templates",
    "Integration Center",
    "Simulated Integration",
    "Interactive representative ERP and accounting mappings and failure scenarios.",
    "No vendor certification, installation, or live synchronization is claimed.",
    "Select a design-partner system and complete adapter certification work.",
  ),
  capability(
    "CAP-SSO-001",
    "Enterprise SSO configuration",
    "Enterprise Access",
    "Simulated Integration",
    "Entra, Okta, and generic SAML metadata and mapping previews.",
    "No external identity provider authenticates the demonstration.",
    "Obtain approved IdP metadata, roles, test users, and activation sign-off.",
  ),
  capability(
    "CAP-SUPPLIER-001",
    "Supplier self-service onboarding",
    "Supplier Governance",
    "Functional Demo",
    "Synthetic supplier invitation, submission, validation, review, remediation, and lifecycle control.",
    "All supplier identities and documents are fictional.",
    "Configure customer-specific requirements and invite approved pilot suppliers.",
  ),
  capability(
    "CAP-BANK-001",
    "Banking change control",
    "Supplier Governance",
    "Functional Demo",
    "Masked synthetic change, independent verification, and dual approval without payment execution.",
    "Ownership is not verified by a real banking provider.",
    "Approve a banking-verification provider and customer control design.",
  ),
  capability(
    "CAP-CONTRACT-001",
    "Contract-document intelligence",
    "Contract Intelligence",
    "Functional Demo",
    "Versioned synthetic document findings, exact citations, obligations, and conflicts.",
    "Deterministic extraction is not legal advice or production OCR.",
    "Approve contract taxonomy, OCR provider, and human-validation procedure.",
  ),
  capability(
    "CAP-WORKFLOW-001",
    "Governed workflow designer",
    "Workflow Studio",
    "Functional Demo",
    "Approved blocks, validation, simulation, independent approval, activation, and rollback.",
    "Arbitrary code, SQL, and unrestricted APIs are unavailable.",
    "Approve customer roles, policies, owners, and workflow authorities.",
  ),
  capability(
    "CAP-MOBILE-001",
    "Responsive approvals and receiving",
    "Mobile Work",
    "Functional Demo",
    "Responsive web approval, receiving, evidence, and discrepancy actions.",
    "Hardware scanning and guaranteed offline operation are simulated.",
    "Complete target-device testing and select any required scanning provider.",
  ),
  capability(
    "CAP-REPORTING-001",
    "Governed Reporting Studio",
    "Reporting Studio",
    "Functional Demo",
    "Certified measures, approved dimensions, drillthrough, snapshots, and reconciled exports.",
    "Scheduled external distribution is simulated.",
    "Approve customer measures, targets, recipients, and distribution provider.",
  ),
  capability(
    "CAP-CATE-001",
    "CATE evidence-backed narrative",
    "CATE",
    "Functional Demo",
    "Permission-aware evidence, certified calculations, fact/inference separation, and safe fallback.",
    "Live provider availability varies by staging configuration.",
    "Approve provider, retention, customer data boundary, and evaluation thresholds.",
  ),
  capability(
    "CAP-TRUST-001",
    "Security and Trust Center",
    "Trust Center",
    "Functional Demo",
    "Implemented controls, internal validation, findings, and activation dependencies.",
    "Internal evidence is not independent certification.",
    "Complete required independent assessment before making certification claims.",
  ),
  capability(
    "CAP-A11Y-001",
    "Accessibility Assurance Center",
    "Accessibility",
    "Functional Demo",
    "WCAG 2.2 AA internal target, critical-route matrix, findings, and retests.",
    "No VPAT, ACR, badge, or independent conformance claim is provided.",
    "Complete approved manual and independent assessments when required.",
  ),
  capability(
    "CAP-OPS-001",
    "Operations Center",
    "Operations",
    "Functional Demo",
    "Truth-labeled health, alert, incident, support, runbook, and fallback scenarios.",
    "Illustrative objectives are not contractual SLAs or support promises.",
    "Approve production monitoring, retention, support hours, and incident commitments.",
  ),
  capability(
    "CAP-VOICE-001",
    "CATE voice narration",
    "Presenter Experience",
    "Functional Demo",
    "Server-side voice is available where configured with browser fallback.",
    "Voice availability is noncritical and never blocks the primary demonstration.",
    "Verify the provider and approved voice before each important demonstration.",
  ),
  capability(
    "CAP-SCIM-001",
    "SCIM provisioning",
    "Enterprise Access",
    "Future Activation",
    "Provisioning lifecycle and mapping concepts are documented.",
    "No account is created, updated, suspended, or removed externally.",
    "Select an IdP, approve provisioning rules, and complete security testing.",
  ),
];

const canonicalEntities: CanonicalEntityDefinition[] = [
  ["organizations", true, false, ["tenant identity"], ["approved reference attributes"]],
  ["users", true, false, ["roles", "scopes", "authority"], ["identity attributes"]],
  ["departments", true, false, ["effective application"], ["master code and name"]],
  ["locations", true, false, ["effective application"], ["master code and name"]],
  ["cost_centers", true, false, ["workflow use"], ["master code and status"]],
  ["suppliers", true, true, ["governance status", "risk"], ["source master attributes"]],
  ["items", true, false, ["procurement controls"], ["catalog attributes"]],
  ["contracts", true, false, ["validated findings", "obligations"], ["document and reference data"]],
  ["budgets", true, false, ["commitment controls"], ["approved budget values"]],
  ["purchase_orders", true, true, ["approval and order record"], ["external posting reference"]],
  ["receipts", true, true, ["accepted quantities and evidence"], ["external receipt reference"]],
  ["invoices", true, false, ["match and exception decision"], ["invoice source values"]],
  ["payment_readiness", false, true, ["readiness decision"], ["payment execution"]],
  ["audit_references", false, true, ["evidence identity and hash"], []],
].map(([entity, inbound, outbound, catalystAuthority, externalAuthority]) => ({
  entity: entity as string,
  inbound: inbound as boolean,
  outbound: outbound as boolean,
  catalystAuthority: catalystAuthority as string[],
  externalAuthority: externalAuthority as string[],
  identityRule: `${entity as string}: external source ID maps to one immutable Catalyst ID`,
}));

const certifiedMeasures: CertifiedMeasure[] = [
  {
    id: "metric-off-contract-spend-rate",
    name: "Addressable off-contract spend rate",
    classification: "guardrail",
    businessDefinition:
      "Addressable posted spend not linked to a validated active contract divided by addressable posted spend.",
    formula: "off_contract_addressable_spend_cents / addressable_posted_spend_cents",
    grain: "posted invoice line",
    owner: "Chief Procurement Officer",
    source: "invoice, purchase order, and validated contract records",
    asOfRule: "Authoritative demonstration clock; posted records only",
    target: "Synthetic demo target ≤ 8.0%",
    exclusions: ["tax-only lines", "non-addressable statutory spend"],
    version: 1,
    lineage: ["invoice line", "purchase order", "contract validation"],
  },
  {
    id: "metric-supplier-risk-exposure",
    name: "High-risk supplier exposure",
    classification: "guardrail",
    businessDefinition:
      "Open commitments with high or critical risk suppliers divided by total open supplier commitments.",
    formula: "high_risk_open_commitment_cents / total_open_commitment_cents",
    grain: "open purchase-order line",
    owner: "Third-Party Risk Owner",
    source: "supplier risk and purchase-order commitments",
    asOfRule: "Current validated supplier status and open commitments",
    target: "Synthetic demo target ≤ 3.0%",
    exclusions: ["closed and cancelled orders"],
    version: 1,
    lineage: ["supplier review", "purchase order", "commitment"],
  },
  {
    id: "metric-contract-notice-exposure",
    name: "Contract notice exposure",
    classification: "outcome",
    businessDefinition:
      "Open commitment value attached to contracts inside the approved notice window without a completed owner action.",
    formula: "sum(open_commitment_cents where notice_window_open and owner_action_open)",
    grain: "contract",
    owner: "Contract Management Lead",
    source: "validated contract deadlines, obligations, and commitments",
    asOfRule: "Demonstration date against validated notice deadline",
    target: "Synthetic demo target $0 unresolved inside 30 days",
    exclusions: ["superseded contract versions"],
    version: 1,
    lineage: ["contract citation", "obligation", "purchase order"],
  },
  {
    id: "metric-first-pass-match",
    name: "First-pass invoice match rate",
    classification: "outcome",
    businessDefinition:
      "Invoices matched without a human exception divided by invoices reaching match review.",
    formula: "first_pass_matched_invoice_count / match_review_invoice_count",
    grain: "invoice",
    owner: "Accounts Payable Lead",
    source: "invoice match and exception records",
    asOfRule: "Invoices reaching match review by the demonstration date",
    target: "Synthetic demo target ≥ 92.0%",
    exclusions: ["duplicate test records", "cancelled invoices"],
    version: 1,
    lineage: ["invoice", "receipt", "purchase order", "match decision"],
  },
  {
    id: "metric-approval-bottleneck-contribution",
    name: "Approval bottleneck contribution",
    classification: "driver",
    businessDefinition:
      "Share of end-to-end approval elapsed time attributable to each governed workflow step.",
    formula: "step_elapsed_business_minutes / total_approval_elapsed_business_minutes",
    grain: "approval step",
    owner: "Procurement Operations",
    source: "workflow instance events",
    asOfRule: "Completed and currently open approval instances",
    target: "No single nonmandatory step above 35%",
    exclusions: ["requester information-wait time"],
    version: 1,
    lineage: ["workflow version", "approval event", "business calendar"],
  },
  {
    id: "metric-integration-reconciliation",
    name: "Integration reconciliation completeness",
    classification: "guardrail",
    businessDefinition:
      "Accepted integration records with matched control totals and lineage divided by accepted records.",
    formula: "reconciled_accepted_record_count / accepted_record_count",
    grain: "integration record",
    owner: "Integration Control Owner",
    source: "integration run and reconciliation records",
    asOfRule: "Latest approved run per connection and batch",
    target: "100%",
    exclusions: ["quarantined rejected records"],
    version: 1,
    lineage: ["source batch", "mapping version", "canonical record", "posting result"],
  },
  {
    id: "metric-evidence-completeness",
    name: "Decision evidence completeness",
    classification: "driver",
    businessDefinition:
      "Material decisions containing every required evidence field divided by material decisions.",
    formula: "complete_material_decision_count / material_decision_count",
    grain: "material decision",
    owner: "Internal Audit",
    source: "audit and evidence records",
    asOfRule: "All material decisions through the demonstration date",
    target: "100%",
    exclusions: [],
    version: 1,
    lineage: ["decision", "policy", "contract", "citation", "audit event"],
  },
  {
    id: "metric-cate-correction-rate",
    name: "CATE material correction rate",
    classification: "guardrail",
    businessDefinition:
      "Material CATE findings requiring factual or numerical correction divided by reviewed material findings.",
    formula: "materially_corrected_cate_findings / reviewed_material_cate_findings",
    grain: "CATE finding",
    owner: "AI Governance Owner",
    source: "CATE evaluation and human feedback",
    asOfRule: "Reviewed evaluation set and demonstration findings",
    target: "Synthetic demo target ≤ 2.0%",
    exclusions: ["copy-only edits"],
    version: 1,
    lineage: ["CATE finding", "citation", "human review", "correction"],
  },
];

const reportDefinitions: ReportDefinition[] = [
  ["report-executive", "Executive procurement performance", ["Executive", "Finance"]],
  ["report-spend", "Spend, commitment, and budget", ["Executive", "Procurement"]],
  ["report-savings", "Savings realization controls", ["Finance", "Procurement"]],
  ["report-supplier", "Supplier performance and risk", ["Procurement", "Risk"]],
  ["report-contract", "Contract renewal and obligation", ["Contract", "Legal liaison"]],
  ["report-cycle", "Approval and cycle-time bottlenecks", ["Operations", "Executive"]],
  ["report-receiving", "Receiving, quality, and delivery", ["Receiving", "Procurement"]],
  ["report-invoice", "Invoice match and AP readiness", ["Accounts Payable", "Finance"]],
  ["report-audit", "Audit, control, and compliance", ["Audit", "Security"]],
  ["report-integration", "Integration and reconciliation health", ["IT", "Finance"]],
].map(([id, name, audience], index) => ({
  id: id as string,
  name: name as string,
  audience: audience as string[],
  measureIds: certifiedMeasures
    .slice(index % 4, (index % 4) + 4)
    .map((measure) => measure.id),
  dimensions: ["fiscal period", "department", "location", "category", "supplier", "status"],
  supportedExports: ["PDF", "XLSX", "CSV"],
  scheduledDistributionStatus: "Simulated Integration",
  accessibleTable: true,
  version: 1,
}));

const assuranceControls: AssuranceControl[] = [
  {
    id: "SEC-TENANT-001",
    domain: "security",
    name: "Tenant and supplier isolation",
    status: "Internally Tested",
    evidence: ["RLS policy suite", "direct cross-tenant denial tests"],
    limitation: "Independent penetration testing remains future activation work.",
    owner: "Security owner",
  },
  {
    id: "SEC-AUTH-002",
    domain: "security",
    name: "Server-authoritative protected actions",
    status: "Implemented",
    evidence: ["Authenticated route handlers", "role and separation-of-duties tests"],
    limitation: "Customer SSO and step-up policy are not activated.",
    owner: "Engineering owner",
  },
  {
    id: "SEC-SUPPLY-003",
    domain: "security",
    name: "Dependency and software inventory",
    status: "Internally Tested",
    evidence: ["Pinned lockfile", "dependency audit", "CycloneDX SBOM"],
    limitation: "Evidence is release-specific and must be regenerated.",
    owner: "Security owner",
  },
  {
    id: "A11Y-KEYBOARD-001",
    domain: "accessibility",
    name: "Keyboard-complete Golden Thread",
    status: "Internally Tested",
    evidence: ["Semantic controls", "focus visibility", "keyboard route matrix"],
    limitation: "Physical assistive-technology verification remains a release gate.",
    owner: "Accessibility owner",
  },
  {
    id: "A11Y-REPORT-002",
    domain: "accessibility",
    name: "Accessible report equivalents",
    status: "Implemented",
    evidence: ["Table equivalents", "text status labels", "non-color meaning"],
    limitation: "Independent accessibility certification is not claimed.",
    owner: "Product owner",
  },
  {
    id: "OPS-FALLBACK-001",
    domain: "operations",
    name: "Provider failure and deterministic fallback",
    status: "Internally Tested",
    evidence: ["CATE fallback tests", "provider outage runbook", "incident scenario"],
    limitation: "Illustrative service objectives are not contractual SLAs.",
    owner: "Operations owner",
  },
];

const runbookDefinitions: Array<[string, string]> = [
  ["runbook-preflight", "Demonstration preflight"],
  ["runbook-reset", "Deterministic demonstration reset"],
  ["runbook-provider-outage", "Provider outage and fallback"],
  ["runbook-integration-failure", "Failed integration and reconciliation"],
  ["runbook-control-total", "Control-total mismatch"],
  ["runbook-auth", "Authentication failure"],
  ["runbook-sso", "SSO configuration problem"],
  ["runbook-document", "Document-processing failure"],
  ["runbook-integrity", "Data-integrity failure"],
  ["runbook-tenant", "Suspected tenant exposure"],
  ["runbook-prompt", "Prompt injection"],
  ["runbook-deploy", "Deployment failure"],
  ["runbook-rollback", "Deployment rollback"],
  ["runbook-restore", "Database restoration"],
  ["runbook-security", "Security incident"],
  ["runbook-accessibility", "Accessibility-blocking defect"],
];

const runbooks: RunbookRecord[] = runbookDefinitions.map(([id, name]) => ({
  id,
  name,
  version: "1.0",
  status: "tested",
  owner: name.includes("Accessibility")
    ? "Accessibility owner"
    : name.includes("Security") || name.includes("tenant")
      ? "Security owner"
      : "Operations owner",
  lastTestedAt: "Release candidate verification required",
  steps: [
    "Confirm the active tenant, release, provider mode, and correlation identifier.",
    "Contain the failure without weakening a protected control.",
    "Use the approved deterministic fallback or rollback target.",
    "Record evidence, owner, result, and required follow-up.",
  ],
}));

const goldenThread: GoldenThreadScene[] = [
  ["executive_signal", "Executive signals", ["Executive", "Finance"], 1.5, "/dashboard", "executive"],
  ["cate_evidence", "CATE explains the evidence", ["Executive", "Procurement"], 1.25, "/ai-procurement", "executive"],
  ["supplier_response", "Supplier responds", ["Procurement", "Supplier"], 1.25, "/supplier-onboarding", "supplier_user"],
  ["supplier_control", "Supplier control and remediation", ["Risk", "Finance"], 1.5, "/supplier-onboarding", "compliance_reviewer"],
  ["contract_deadline", "Contract deadline and price conflict", ["Contract", "Finance"], 1.75, "/contract-intelligence", "contract_manager"],
  ["request_evaluation", "Connected request evaluation", ["Procurement", "Finance"], 1.25, "/purchase-requests", "requester"],
  ["workflow_routing", "Governed workflow routing", ["Procurement", "IT"], 1.5, "/workflow-studio", "purchasing_manager"],
  ["mobile_approval", "Mobile approval", ["Approver"], 1, "/mobile-work", "department_manager"],
  ["receiving_discrepancy", "Mobile receiving discrepancy", ["Receiving"], 1.25, "/mobile-work", "receiving_clerk"],
  ["invoice_exception", "Invoice exception", ["Accounts Payable", "Finance"], 1.25, "/invoices", "accounts_payable"],
  ["integration_reconciliation", "Integration reconciliation", ["IT", "Finance"], 1.5, "/integration-center", "system_administrator"],
  ["executive_report", "Evidence-backed report pack", ["Executive", "Finance"], 1.5, "/reporting-studio", "executive"],
  ["trust_evidence", "Security and trust evidence", ["Security", "Audit"], 1, "/trust-center", "security_reviewer"],
  ["accessibility_evidence", "Accessibility evidence", ["Accessibility", "Product"], 0.75, "/accessibility-center", "auditor"],
  ["operations_fallback", "Operations fallback", ["Operations", "IT"], 1.25, "/operations-center", "operations_manager"],
  ["pilot_activation", "Controlled pilot activation path", ["Executive", "IT"], 0.75, "/golden-thread", "executive"],
].map(([id, title, audience, recommendedMinutes, route, persona]) => ({
  id: id as GoldenThreadScene["id"],
  title: title as string,
  audience: audience as string[],
  recommendedMinutes: recommendedMinutes as number,
  route: route as string,
  persona: persona as string,
  talkingPoints: [
    `Show ${title as string} using the same authoritative synthetic scenario.`,
    "Explain the human authority, evidence, and truth-status boundary.",
  ],
  proofPoints: [
    "Source record and version",
    "Correlation-linked audit evidence",
    "Visible capability status and limitation",
  ],
  limitationReminder:
    "This is a synthetic commercialization demonstration, not a live customer pilot.",
  fallbackInstruction:
    "Use the deterministic scene state and explain any unavailable provider honestly.",
  status: "ready",
}));

export function createPhaseThreeState(
  sessionDate: string,
  tenantId: string,
): PhaseThreeState {
  const tomorrow = addCalendarDays(sessionDate, 1);
  const contractDeadline = addCalendarDays(sessionDate, 18);
  const insuranceExpiration = addCalendarDays(sessionDate, -4);
  const correlation = "11111111-1111-4111-8111-111111111111";
  const tenantPrefix = tenantId === "org-y12-demo" ? "Y12" : "CCCU";

  return {
    schemaVersion: 1,
    dataset: {
      version: PHASE_THREE_DATASET_VERSION,
      schemaVersion: 1,
      contentHash: PHASE_THREE_DATASET_HASH,
      demonstrationDate: sessionDate,
      expectedRecordCounts: {
        capabilities: phaseThreeCapabilityRegistry.length,
        canonicalEntities: canonicalEntities.length,
        suppliers: 2,
        contractVersions: 1,
        workflowVersions: 2,
        certifiedMeasures: certifiedMeasures.length,
        reports: reportDefinitions.length,
        goldenThreadScenes: goldenThread.length,
      },
      expectedTotals: {
        integrationSourceTotalCents: 125_000_000,
        integrationPostedTotalCents: 124_500_000,
        proposedContractIncreaseBasisPoints: 650,
        contractIncreaseLimitBasisPoints: 300,
      },
      expectedOutcomes: [
        "One integration control-total mismatch is detected and safely replayed.",
        "One supplier remains blocked pending insurance remediation.",
        "One price escalation above the contract limit is routed to a human.",
        "One governed high-risk workflow is validated, approved, and activated.",
        "CATE and provider failures enter visibly labeled deterministic fallback.",
      ],
    },
    capabilityRegistry: structuredClone(phaseThreeCapabilityRegistry),
    canonicalEntities,
    integrations: [
      {
        connectionKey: "reference-file-exchange",
        name: "Catalyst secure file reference flow",
        adapterKey: "canonical-csv-v1",
        truthStatus: "Functional Demo",
        lifecycleState: "ready",
        mappingVersion: 1,
        sourceOfTruth: {
          supplier_master: "External",
          procurement_status: "Catalyst",
          payment_execution: "External",
        },
        mappings: [
          {
            sourceField: "vendor_number",
            canonicalField: "supplier.externalId",
            transformation: "trim + preserve source",
            required: true,
            status: "mapped",
          },
          {
            sourceField: "legal_name",
            canonicalField: "supplier.legalName",
            transformation: "unicode normalize",
            required: true,
            status: "mapped",
          },
          {
            sourceField: "risk_code",
            canonicalField: "supplier.sourceRiskReference",
            transformation: "preserve; Catalyst risk remains authoritative",
            required: false,
            status: "warning",
          },
        ],
        activationRequirements: [
          "Approved transport and credential exchange",
          "Customer data dictionary and control totals",
          "Sandbox reconciliation and rollback sign-off",
        ],
        lastTestedAt: timestamp(sessionDate, 12),
      },
      ...([
        ["sap-template", "SAP representative pattern", "erp-sap-sim-v1"],
        ["oracle-template", "Oracle representative pattern", "erp-oracle-sim-v1"],
        ["netsuite-template", "NetSuite representative pattern", "accounting-netsuite-sim-v1"],
      ] as const).map(([connectionKey, name, adapterKey]) => ({
        connectionKey,
        name,
        adapterKey,
        truthStatus: "Simulated Integration" as const,
        lifecycleState: "tested" as const,
        mappingVersion: 1,
        sourceOfTruth: {
          master_data: "External" as const,
          procurement_decisions: "Catalyst" as const,
          financial_posting: "External" as const,
        },
        mappings: [
          {
            sourceField: "external_id",
            canonicalField: "canonical.externalId",
            transformation: "versioned template",
            required: true,
            status: "mapped" as const,
          },
        ],
        activationRequirements: [
          "Design-partner system selection",
          "Approved sandbox credentials",
          "Vendor-specific contract and reconciliation tests",
        ],
        lastTestedAt: timestamp(sessionDate, 11),
      })),
    ],
    integrationRuns: [
      {
        id: "integration-run-mismatch",
        connectionKey: "reference-file-exchange",
        batchId: `${tenantPrefix}-ERP-IN-00041`,
        direction: "inbound",
        status: "dead_letter",
        recordCount: 250,
        acceptedCount: 249,
        rejectedCount: 1,
        sourceTotalCents: 125_000_000,
        postedTotalCents: 124_500_000,
        mappingVersion: 1,
        sourceTimestamp: timestamp(addCalendarDays(sessionDate, -1), 22),
        ingestionTimestamp: timestamp(sessionDate, 8),
        contentHash:
          "600ba3d6d03638d84b1d4855c93c6e475bac3edb5007d5cf555a116d3d515c16",
        checkpoint: "row-249",
        retryCount: 2,
        validationFindings: [
          "Control total differs by $5,000.00.",
          "Row 250 references an inactive cost center and is quarantined.",
        ],
        reconciliation:
          "Posting stopped before external confirmation; safe replay is available after correction.",
        correlationId: correlation,
        simulated: true,
      },
      {
        id: "integration-run-reconciled",
        connectionKey: "reference-file-exchange",
        batchId: `${tenantPrefix}-ERP-IN-00040`,
        direction: "inbound",
        status: "reconciled",
        recordCount: 248,
        acceptedCount: 248,
        rejectedCount: 0,
        sourceTotalCents: 122_850_000,
        postedTotalCents: 122_850_000,
        mappingVersion: 1,
        sourceTimestamp: timestamp(addCalendarDays(sessionDate, -2), 22),
        ingestionTimestamp: timestamp(addCalendarDays(sessionDate, -1), 8),
        contentHash:
          "463f80391516faae42e4a3abef47c3f87a080f0e3d39749de3462af7073ba0df",
        checkpoint: "complete",
        retryCount: 0,
        validationFindings: [],
        reconciliation:
          "Record counts, identifiers, lineage, and control totals reconcile.",
        correlationId: "22222222-2222-4222-8222-222222222222",
        simulated: true,
      },
    ],
    ssoTemplates: [
      {
        id: "entra",
        name: "Microsoft Entra ID",
        truthStatus: "Simulated Integration",
        domain: "prospect.example",
        entityId: "urn:catalyst:phase3:entra:synthetic",
        callbackUrl: "https://phase3-demo.example/auth/sso/callback",
        attributeMappings: [
          ["email", "identity.email"],
          ["displayName", "identity.displayName"],
          ["objectId", "identity.externalSubject"],
        ],
        groupMappings: [
          ["Catalyst-Procurement-Approvers", "approver candidate"],
          ["Catalyst-Procurement-Auditors", "auditor candidate"],
        ],
        testStatus: "passed",
        activationChecklist: [
          "Approved IdP metadata and certificate",
          "Named test users and emergency local account",
          "Catalyst role/scope review and customer sign-off",
        ],
        catalystAuthorityStatement:
          "Identity claims propose membership; Catalyst tenant, role, scope, and approval authority remain authoritative.",
      },
      {
        id: "okta",
        name: "Okta",
        truthStatus: "Simulated Integration",
        domain: "prospect.example",
        entityId: "urn:catalyst:phase3:okta:synthetic",
        callbackUrl: "https://phase3-demo.example/auth/sso/callback",
        attributeMappings: [
          ["email", "identity.email"],
          ["firstName", "identity.givenName"],
          ["lastName", "identity.familyName"],
        ],
        groupMappings: [["Procurement-Users", "requester candidate"]],
        testStatus: "passed",
        activationChecklist: [
          "Approved Okta application",
          "Signed attribute and group mapping",
          "Negative authorization tests",
        ],
        catalystAuthorityStatement:
          "Okta proves identity only; Catalyst authorizes procurement actions.",
      },
      {
        id: "saml",
        name: "Generic SAML 2.0",
        truthStatus: "Simulated Integration",
        domain: "prospect.example",
        entityId: "urn:catalyst:phase3:saml:synthetic",
        callbackUrl: "https://phase3-demo.example/auth/sso/callback",
        attributeMappings: [["NameID", "identity.email"]],
        groupMappings: [],
        testStatus: "passed",
        activationChecklist: [
          "Metadata exchange",
          "Certificate validation",
          "Access review and emergency access verification",
        ],
        catalystAuthorityStatement:
          "SAML assertions cannot override Catalyst tenant membership or authority.",
      },
    ],
    supplierApplications: [
      {
        id: "supplier-application-blue-ridge",
        supplierId: "vendor-003",
        supplierName: "Blue Ridge Network Solutions",
        supplierOrganizationId: "supplier-org-blue-ridge",
        lifecycleState: "active",
        riskTier: "low",
        documentStatus: "current",
        documents: [
          {
            id: "doc-blue-ridge-insurance",
            name: "Synthetic certificate of insurance",
            synthetic: true,
            status: "current",
            expiresAt: addCalendarDays(sessionDate, 220),
          },
          {
            id: "doc-blue-ridge-tax",
            name: "Synthetic tax document placeholder",
            synthetic: true,
            status: "current",
          },
        ],
        validationFindings: [],
        reviews: ["purchasing", "compliance", "finance", "security", "category"].map(
          (domain) => ({
            domain: domain as
              | "purchasing"
              | "compliance"
              | "finance"
              | "security"
              | "category",
            status: "approved" as const,
            reviewer: `${domain} reviewer`,
            rationale: "Required synthetic evidence is complete and current.",
          }),
        ),
        remediationItems: [],
        version: 3,
        correlationId: "33333333-3333-4333-8333-333333333333",
      },
      {
        id: "supplier-application-volunteer",
        supplierId: "vendor-001",
        supplierName: "Volunteer Technology Partners",
        supplierOrganizationId: "supplier-org-volunteer",
        lifecycleState: "information_required",
        riskTier: "high",
        documentStatus: "expired",
        documents: [
          {
            id: "doc-volunteer-insurance",
            name: "Synthetic certificate of insurance",
            synthetic: true,
            status: "expired",
            expiresAt: insuranceExpiration,
          },
          {
            id: "doc-volunteer-cyber",
            name: "Synthetic cybersecurity attestation",
            synthetic: true,
            status: "missing",
          },
        ],
        validationFindings: [
          `Insurance expired ${insuranceExpiration}.`,
          "Cybersecurity attestation is missing.",
          "Supplier remains ineligible for award pending remediation.",
        ],
        reviews: [
          {
            domain: "purchasing",
            status: "information_required",
            reviewer: "Purchasing reviewer",
            rationale: "Required evidence is incomplete.",
          },
          {
            domain: "compliance",
            status: "information_required",
            reviewer: "Compliance reviewer",
            rationale: "Expired insurance blocks approval.",
          },
          { domain: "finance", status: "pending" },
          { domain: "security", status: "information_required" },
          { domain: "category", status: "pending" },
        ],
        remediationItems: [
          "Upload a current synthetic insurance certificate.",
          "Complete the synthetic cybersecurity attestation.",
        ],
        bankingChange: {
          id: "bank-change-volunteer-001",
          proposedLastFour: "1842",
          proposedBy: "supplier-user-volunteer",
          status: "verification_pending",
          paymentInitiated: false,
        },
        version: 2,
        correlationId: "44444444-4444-4444-8444-444444444444",
      },
    ],
    contracts: [
      {
        id: "contract-intelligence-managed-network-v2",
        contractId: "contract-001",
        contractName: "Managed Network Services Agreement",
        supplierId: "vendor-001",
        documentVersion: 2,
        documentHash:
          "96f65c9f033de2a7de860b6ef387ebfb7a01f957cd85dd950ef53c8da0021836",
        storagePath:
          `${tenantId}/contracts/contract-001/v2/managed-network-services-agreement-v2.pdf`,
        lifecycleState: "review_required",
        extractionMethod: "deterministic_demo",
        findings: [
          {
            id: "finding-cancellation-notice",
            type: "cancellation",
            finding: `Written non-renewal notice is due ${contractDeadline}.`,
            interpretation:
              "The owner should decide whether to renew or issue notice before the cited deadline.",
            citation: {
              documentId: "contract-001",
              documentVersion: 2,
              page: 12,
              clause: "Section 8.2 – Renewal and Notice",
              boundedPassage:
                "Either party may prevent renewal by providing written notice no fewer than ninety days before the renewal date.",
            },
            confidence: "high",
            validationStatus: "pending",
          },
          {
            id: "finding-price-escalation",
            type: "price_escalation",
            finding: "Annual price escalation is capped at 3.00%.",
            interpretation:
              "The supplier proposal of 6.50% exceeds the cited contractual cap by 3.50 percentage points.",
            citation: {
              documentId: "contract-001",
              documentVersion: 2,
              page: 7,
              clause: "Section 5.4 – Annual Adjustment",
              boundedPassage:
                "Any annual adjustment shall not exceed three percent of the then-current recurring service charges.",
            },
            confidence: "high",
            validationStatus: "pending",
          },
          {
            id: "finding-security-evidence",
            type: "security",
            finding: "Annual independent security evidence is required.",
            interpretation:
              "The contract owner must collect and validate the required evidence; CATE cannot accept it.",
            citation: {
              documentId: "contract-001",
              documentVersion: 2,
              page: 18,
              clause: "Exhibit C, Section 3 – Security Assurance",
              boundedPassage:
                "Provider shall furnish current independent security assessment evidence annually upon request.",
            },
            confidence: "moderate",
            validationStatus: "pending",
          },
        ],
        obligations: [
          {
            id: "obligation-renewal-decision",
            findingId: "finding-cancellation-notice",
            owner: "Contract Management Lead",
            dueDate: addBusinessDays(contractDeadline, -5),
            recurrence: "annual",
            status: "open",
            evidence: [],
            reminderStatus: "scheduled",
          },
          {
            id: "obligation-security-evidence",
            findingId: "finding-security-evidence",
            owner: "Third-Party Security Owner",
            dueDate: addBusinessDays(sessionDate, 12),
            recurrence: "annual",
            status: "in_progress",
            evidence: ["Synthetic evidence request prepared"],
            reminderStatus: "sent_simulated",
          },
        ],
        conflicts: [
          {
            id: "conflict-price-increase",
            type: "purchase_order_price",
            severity: "blocked",
            explanation:
              "The proposed 6.50% increase exceeds the validated 3.00% contractual limit.",
            sourceRecordIds: [
              "contract-001:v2:section-5.4",
              "supplier-proposal-2026-07",
              "purchase-order-forecast-2026",
            ],
            requiredHumanAction:
              "Contract manager validates the clause and purchasing negotiates or records an approved exception.",
            status: "open",
          },
          {
            id: "conflict-renewal-deadline",
            type: "deadline",
            severity: "warning",
            explanation:
              "The notice deadline is approaching and no completed renewal decision is recorded.",
            sourceRecordIds: ["contract-001:v2:section-8.2", "obligation-renewal-decision"],
            requiredHumanAction:
              "Assigned owner records a renewal or non-renewal decision with evidence.",
            status: "open",
          },
        ],
        correlationId: "55555555-5555-4555-8555-555555555555",
      },
    ],
    workflowVersions: [
      {
        id: "workflow-high-risk-purchase-v1",
        workflowKey: "high-risk-purchase-approval",
        name: "High-value and high-risk purchase approval",
        family: "purchase_approval",
        version: 1,
        lifecycleState: "draft",
        blocks: [
          { id: "start", type: "start", label: "Request submitted", next: ["risk-check"] },
          {
            id: "risk-check",
            type: "condition",
            label: "Amount ≥ $50,000 or supplier risk is high",
            condition: "amount_cents >= 5000000 OR supplier_risk IN (high, critical)",
            next: ["procurement-review", "standard-approval"],
          },
          {
            id: "procurement-review",
            type: "specialist_review",
            label: "Procurement review",
            ownerRole: "purchasing_manager",
            next: ["compliance-review"],
          },
          {
            id: "compliance-review",
            type: "specialist_review",
            label: "Independent compliance review",
            ownerRole: "compliance_reviewer",
            next: ["executive-approval"],
          },
          {
            id: "executive-approval",
            type: "sequential_approval",
            label: "Executive approval",
            ownerRole: "executive",
            next: ["end-approved"],
          },
          {
            id: "standard-approval",
            type: "sequential_approval",
            label: "Standard approval",
            ownerRole: "department_manager",
            next: ["end-approved"],
          },
          { id: "end-approved", type: "end", label: "Approved outcome", next: [] },
        ],
        validationFindings: [],
        authoredBy: "user-liam",
        correlationId: "66666666-6666-4666-8666-666666666666",
      },
      {
        id: "workflow-standard-purchase-v3",
        workflowKey: "standard-purchase-approval",
        name: "Standard purchase approval",
        family: "purchase_approval",
        version: 3,
        lifecycleState: "active",
        blocks: [
          { id: "start", type: "start", label: "Request submitted", next: ["manager"] },
          {
            id: "manager",
            type: "sequential_approval",
            label: "Department manager",
            ownerRole: "department_manager",
            next: ["end"],
          },
          { id: "end", type: "end", label: "Approved outcome", next: [] },
        ],
        validationFindings: [],
        simulationResult: "All synthetic standard transactions reach one controlled outcome.",
        authoredBy: "user-maya",
        approvedBy: "user-elena",
        effectiveAt: timestamp(addCalendarDays(sessionDate, -90), 9),
        correlationId: "77777777-7777-4777-8777-777777777777",
      },
    ],
    mobileTasks: [
      {
        id: "mobile-approval-featured",
        type: "approval",
        sourceRecordId: "req-loan-officer-package",
        assigneeRole: "department_manager",
        status: "assigned",
        evidence: [
          "Budget result",
          "Supplier eligibility",
          "Contract coverage",
          "Policy findings",
          "CATE evidence",
        ],
        updatedAt: timestamp(sessionDate, 9),
      },
      {
        id: "mobile-receiving-featured",
        type: "receiving",
        sourceRecordId: "po-featured",
        assigneeRole: "receiving_clerk",
        status: "assigned",
        evidence: ["Synthetic packing slip", "Approved synthetic damage photograph"],
        simulationDisclosure:
          "Barcode/QR capture is simulated. The resulting synthetic receipt state is functional.",
        updatedAt: timestamp(sessionDate, 9),
      },
    ],
    certifiedMeasures,
    reportDefinitions,
    reportSnapshots: [],
    cateNarratives: [],
    assuranceControls,
    assuranceFindings: [
      {
        id: "finding-a11y-device-validation",
        domain: "accessibility",
        controlId: "A11Y-KEYBOARD-001",
        severity: "Medium",
        status: "open",
        evidence: ["Automated semantics pass", "Desktop keyboard path pass"],
        failureScenario:
          "Physical VoiceOver and Android screen-reader evidence is not yet attached to this release.",
        owner: "Accessibility owner",
        remediation:
          "Complete and record the approved physical-device assistive-technology matrix.",
        dueDate: tomorrow,
        releaseEffect: "Blocks Phase 3 release qualification until retested or explicitly accepted.",
        correlationId: "88888888-8888-4888-8888-888888888888",
      },
      {
        id: "finding-security-independent-assessment",
        domain: "security",
        controlId: "SEC-TENANT-001",
        severity: "Low",
        status: "accepted",
        evidence: ["Internal RLS and authorization suite"],
        failureScenario:
          "No independent penetration assessment has been completed for the demonstration.",
        owner: "Security owner",
        remediation:
          "Retain the independent-validation-required label and complete an assessment before making an independent claim.",
        residualRisk:
          "Internal evidence cannot provide independent assurance.",
        acceptanceAuthority: "Product owner",
        releaseEffect: "Disclosed limitation; does not authorize certification language.",
        correlationId: "99999999-9999-4999-8999-999999999999",
      },
    ],
    operationsSignals: [
      {
        id: "signal-app",
        domain: "application",
        status: "healthy",
        truthStatus: "Functional Demo",
        message: "Release-specific application health must be verified after deployment.",
        asOf: timestamp(sessionDate, 10),
      },
      {
        id: "signal-db",
        domain: "database",
        status: "healthy",
        truthStatus: "Functional Demo",
        message: "Supabase authority, RLS, and private evidence are configured where verified.",
        asOf: timestamp(sessionDate, 10),
      },
      {
        id: "signal-integration",
        domain: "integration",
        status: "degraded",
        truthStatus: "Simulated Integration",
        message: "Reference batch has a controlled total mismatch and is safely dead-lettered.",
        asOf: timestamp(sessionDate, 10),
      },
      {
        id: "signal-cate",
        domain: "cate",
        status: "healthy",
        truthStatus: "Functional Demo",
        message: "CATE remains available with deterministic fallback.",
        asOf: timestamp(sessionDate, 10),
      },
      {
        id: "signal-provider",
        domain: "provider",
        status: "simulated",
        truthStatus: "Simulated Integration",
        message: "ERP, SSO, scanning, scheduling, and support delivery providers are simulated.",
        asOf: timestamp(sessionDate, 10),
      },
    ],
    incidents: [
      {
        id: "incident-cate-provider-001",
        title: "CATE live provider latency exceeds demo threshold",
        severity: "SEV-3",
        status: "detected",
        impact:
          "Live narrative may be delayed; deterministic evidence-backed narrative remains available.",
        owner: "Operations owner",
        evidence: ["Provider timeout event", "Fallback activation record"],
        runbookId: "runbook-provider-outage",
        communicationStatus: "draft_simulated",
        correlationId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
      },
    ],
    supportCases: [
      {
        id: "support-case-integration-001",
        requester: "Synthetic integration reviewer",
        priority: "high",
        impact: "Reference import cannot post until the control total reconciles.",
        category: "integration",
        affectedRecordId: "integration-run-mismatch",
        status: "triaged",
        assignee: "Integration Control Owner",
        evidence: ["Rejected-row extract", "Control-total comparison"],
        responsePreview:
          "Simulated response preview: the batch remains safely stopped while the inactive cost center is corrected.",
        linkedIncidentId: undefined,
        correlationId: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",
      },
    ],
    runbooks,
    goldenThread,
    activeSceneId: "executive_signal",
    preflightChecks: [
      {
        id: "preflight-dataset",
        name: "Dataset version and integrity",
        status: "not_run",
        evidence: PHASE_THREE_DATASET_VERSION,
        blocking: true,
      },
      {
        id: "preflight-truth",
        name: "Capability truth reconciliation",
        status: "not_run",
        evidence: `${phaseThreeCapabilityRegistry.length} registered capabilities`,
        blocking: true,
      },
      {
        id: "preflight-phase2",
        name: "Inherited Phase 2 regression",
        status: "not_run",
        evidence: PHASE_THREE_RELEASE_BASELINE,
        blocking: true,
      },
      {
        id: "preflight-providers",
        name: "Provider modes and deterministic fallback",
        status: "not_run",
        evidence: "Live providers are optional; fallbacks are required.",
        blocking: true,
      },
      {
        id: "preflight-release",
        name: "Exact deployment and rollback evidence",
        status: "not_run",
        evidence: "Recorded only after isolated staging deployment.",
        blocking: true,
      },
      {
        id: "preflight-a11y",
        name: "Target-device accessibility evidence",
        status: "warning",
        evidence: "Physical-device matrix remains open.",
        blocking: true,
      },
    ],
    auditEvents: [
      {
        id: "phase3-audit-seed",
        action: "phase3.dataset.initialized",
        recordType: "synthetic_dataset",
        recordId: PHASE_THREE_DATASET_VERSION,
        activePersona: "system_administrator",
        before: "not_initialized",
        after: "initialized",
        reason: "Create the approved commercialization demonstration baseline.",
        source: "workflow",
        truthStatus: "Functional Demo",
        simulation: false,
        governingVersion: PHASE_THREE_DATASET_VERSION,
        evidence: [PHASE_THREE_DATASET_HASH],
        correlationId: "cccccccc-cccc-4ccc-8ccc-cccccccccccc",
        timestamp: timestamp(sessionDate, 8),
      },
    ],
    providerModes: {
      supabase: "deterministic",
      cate: "deterministic",
      voice: "deterministic",
      integrations: "simulated",
    },
    truthDisclosures: [
      "The organization, people, suppliers, documents, transactions, findings, savings, risks, forecasts, and outcomes are synthetic.",
      "Simulated integrations do not connect to customer systems or perform external actions.",
      "CATE advises with evidence; authorized people retain every protected decision.",
      "Illustrative service objectives are not contractual SLAs.",
      "Security and accessibility results are internal unless an independent assessment is explicitly recorded.",
      "This commercialization demonstration is not a live customer pilot or production customer environment.",
    ],
    lastResetAt: timestamp(sessionDate, 8),
  };
}
