[theme]
primaryColor = "#CF4427"
backgroundColor = "#F7F6F1"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#101B3B"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true

